### ISSUE TITLE
Lokales git einrichten

### ISSUE THREAD

**Issue by JohannMarthaus** [tBuddy00/Follow-Me-Roboter#16]
Genauso, wenn nicht moch mehr braucht jeder ein funktionierendes git.

Richtet euch das bitte alle ein.
Wie das geht ist im ersten SE-Praktikum enthalten
https://www.informatik.htw-dresden.de/~zirkelba/praktika/se/arbeiten-mit-git-und-asciidoc/praktikumsaufgaben-teil-01.html

Wer das schon hat braucht nur noch unter diesem issue kommentieren:
'Eingerichtet und funktioniert.'

**Comment by JohannMarthaus** [comment]
Eingerichtet und funktioniert

**Comment by LucaKurth** [comment]
Eingerichtet und funktioniert

**Comment by tBuddy00** [comment]
Eingerichtet und funktioniert

**Comment by tBuddy00** [comment]
Eingerichtet und funktioniert.

**Comment by CarloPalermo** [comment]
Eingerichtet und funktioniert.

**Comment by cl-ire** [comment]
Eingerichtet und funktioniert
