### ISSUE TITLE
Codeformatierungs Guildlines

### ISSUE THREAD

**Issue by cl-ire** [tBuddy00/Follow-Me-Roboter#3]
Wir brauchen eine allgemeine Richtlinie, wir wir Code formatieren und kommentieren wollen. Und wir müssen dafür eine Guidline als Dokument anlegen.

- Nur mal gebessert wegen Rechtschreibung (Hoffe das ist i. O. Claire?) 

VG. 

Taylan

**Comment by cl-ire** [comment]
https://marketplace.visualstudio.com/items?itemName=ms-python.auto

**Comment by JohannMarthaus** [comment]
Die Entscheidung ist im Gespräch mit Claire auf den pep8 Standard gefallen

**Comment by tBuddy00** [comment]
Dementsprechend ist dann dieses Issue obsolet und kann dann auf "Done" gesetzt werden?

**Comment by JohannMarthaus** [comment]
Mehr oder weniger. Halten wir das noch an irgendeiner Stelle fest? 
Und verlinken die Seite zu pep8 von python.org

**Comment by tBuddy00** [comment]
Ich denke das ist geklärt. @cl-ire gehst du dem bezüglich mit?. Meiner Ansicht nach behalten wir den Standard bei, wir wollen ja konsistent arbeiten.

Und ja, wir verlinken die Seite zu pep8, aber gucken wir wo wir das machen.

**Comment by JohannMarthaus** [comment]
👍🏻 alles klar 
--> wer es dann dokumentiert schließt damit einhergehend auch das issue?!

**Comment by tBuddy00** [comment]
@theresahtw arbeitest du das mit ein?
