### ISSUE TITLE
developer diary

### ISSUE THREAD

**Issue by cl-ire** [tBuddy00/Follow-Me-Roboter#4]
das developer diery solte in etwa so aufgebaut sein 

REDME.md https://github.com/tBuddy00/Follow-Me-Roboter/tree/main/Documentation/developer%20diary
- header des ganzen enthält links zu den einzelnen iterationen

Iteration 1 https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/Documentation/developer%20diary/Iteration%201.adoc
- enthält am ende einen link zur nächsten iteration und am anfang einen link zum header 

Iteration 2 https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/Documentation/developer%20diary/Iteration%202.adoc

**Comment by cl-ire** [comment]
ich hab die readme nochmal verschoben macht denke meher sin 
neuer link https://github.com/tBuddy00/Follow-Me-Roboter/tree/main/Documentation#readme

**Comment by tBuddy00** [comment]
Muss geklärt werden mit Herr Zirkelbach.
