### ISSUE TITLE
Test Bewegungscalkulation

### ISSUE THREAD

**Issue by cl-ire** [tBuddy00/Follow-Me-Roboter#43]
Erstellung eines Tests + Dokumentation zum testen wie akurat die Kalkulationen für die bewegungssteuerung sind

Forgaben 

* für den test wird nur das arduino und ein Pc mit Blothouth verwendet 

Auf dem Arduino 

* Verwendeter code https://github.com/tBuddy00/Follow-Me-Roboter/tree/main/src/Arduino/Skript
* der code ist der standart code der auch im Prototyp verwendet wird
* Ausstatung: Arduino Uno mit Adafruit Motor Shield v2.3. + bloutooth module HC-05; aber ohne das der Jetson Nano verbunden ist
* das bloutooth module ist ein ergenzungs modul das in der normalen produktionsumgebung nicht verwendet wird 

Auf dem Pc

* der verwendete code ist hier zu finden https://github.com/tBuddy00/Follow-Me-Roboter/tree/main/src/Arduino/Test
* vor starten des tests muss Der Pc mit dem Arduino verbunden werde über bloutooth (Paswort: 1234) (Bild einfügen https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/Documentation/test/Movement_calculation_test/conect_bloutooth.png) 
* dann muss der com Port des Arduinos Herausgefunden werden z.B. mitels der arduino ide (Bild einfügen https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/Documentation/test/Movement_calculation_test/arduino_ide_find_out_com_port_1.png) und dann teten der conection mit dem serial monitor (Bild einfügen https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/Documentation/test/Movement_calculation_test/arduino_ide_find_out_com_port_2.png)
* dann mus der Port im code am Pc angepast werden 
* dann kann der Test gestarted werden 
* das program fodert einen dann auf 3 bis 4 werte einzugeben 
* die base RPM (basis geschwindigkeit)
* den winkel 
* und ob sich der roboter von der stelle bewegen soll oder nicht 
* sowie bei komplet gerader bewegung wie lange sich der robotter vorwerts bewegen soll 

Durchführung

 (Bild einfügen https://github.com/tBuddy00/Follow-Me-Roboter/blob/main/Documentation/test/Movement_calculation_test/movement_calculation_test.png)
* Das arduino wird auf dem boden gestelt und mit Klebeband wird die position der räder dokumentiert 
* man gibt dan die oben genaten parameter ein und mist mit begin absendung des letzen parameters die zeit bis der roboter stehen bleibt 
* diese wird dabei mit dem 3 wert der in der konsole zurückkomt verglichen (Beispiel werte -100,100,500,0,0  die 500 ist die zeit in milli sekunden) und beide werte werden in eine exel tabelle eingetragen 
* dann wird die neue position des roboters mit klebeband markiert und der winkel zur alten position gemessen 
* dieser wert wird dan mit dem eigegebenen wert verglichen und beides wird in die exel tabele eingetragen 
* dies wird dann für mehrere werte durchgeführt und es wird der prozentuale durchschint zwischen gemmesenen wert und eigegeben wert verglichen und dann davon der durschnit gebildet 

Weitere aufgaben 

wenn die dokumentation für den test steht währe es eventuel sinvol das aktuelle script um eine log funktion zu erweitern 
was muss hinzugefügt werden:
* nach jedem durchngang wird der nutzer aufgefordert die gemmesenen werte einzutragen 
* die Eingegebenen und gemessenen werte werden nach jedem durchgang zu einer liste hinzugefügt 
* wenn der test beendet wird berechnet das skript automatisch die genauigkeit aus den in der liste gespeicherten werten und bildet den durchschnitt 
* dannach soll der durchschnitt sowie eine auflistung aller durchgänge in der console ausgegeben werden 

auserdem muss ein dokument vorbereitet werden was als vorgabe zur durchführungsdokumentation dient 
* es muss dabei platz geben bilder vom test einzufügen
* den autmatisch generierten log einzufügen
* und den test auszuerten

**Comment by Jedazi** [comment]
Bei mir hat es am Wochenende den Blutetooth empfänger zerhauen und allgemeine Frage, brauche ich für die tests nicht den arduino ?

**Comment by Jedazi** [comment]
Noch paar fragen, 1. Muss noch komplett neuer code für den test erstellt werden oder vorhandener lediglich erweitert ? (falls ja welcher abschnitt?),2. wo soll das Dokument für die Tests erstellt werden ?

**Comment by Jedazi** [comment]
langeweile
