### ISSUE TITLE
Umfrage: Erfahrungen mit Python und Bilderkennung

### ISSUE THREAD

**Issue by JohannMarthaus** [tBuddy00/Follow-Me-Roboter#5]
Nachricht an @JohannMarthaus
Inhalt:
In 3-5 Stichpunkten was ihr bisher konkret für das Projekt gemacht habt.

Bsp.:
- opencv tutorial angefangen (1h 30 min von 3h 40 min) https://www.youtube.com/watch?v=oXlwWbU8l2o
- (sichere Programmierumgebung in VM erstellt)
- Beispielskripte recherchiert und getestet
- Skripte bearbeitet (chatGPT), erneut getestet und erste Problemstellungen herausgearbeitet

Desweitern eine kurze Selbsteinschätzung hinsichtlich der Programmierfähigkeiten mit Python und Kurzbeschreibung der letzten zwei Programme die ihr in Python geschrieben habt (sofern vorhanden). Wenn möglich auch gerne den Code mitschicken.

Bsp.:
- fortgeschrittene Kenntnisse
- Programm 1: Nutzereingabe von Preis und Anzahl eines Produktes, Ausgabe Preis, Rabatt und Preis nach Abzug des Rabattes
- Programm 2: Schlüsselverwaltungssystem mit GUI (noch in Arbeit)

**Comment by LucaKurth** [comment]
- opencv tutorial angefangen (3h von 3h 40 min)
- Beispielskripte recherchiert

Selbsteinschätzung
- Anfänger

**Comment by JohannMarthaus** [comment]
Was für Programme (egal wie klein) hast du schon mit Python geschrieben? Welche packages hast du dabei benutzt?

**Comment by CarloPalermo** [comment]
- opencv tutorial angefangen (1h 30 min von 3h 40 min)

- (sichere Programmierumgebung in VM erstellt)

- Beispielskripte recherchiert und getestet

Selbsteinschätzung: 

- Anfänger 
- Datenvorverarbeitung für simple "Gesichtserkennung" von Hund und Katze (nur die Vorarbeit, d.h. Bilder gleich schneiden und als Tensor ausgeben lassen)
- Basic Programme um OOP bisschen zu lernen (nicht der Rede wert)

**Comment by Jedazi** [comment]
- Grundlegend über Python informiert
- Opencv Tutorial angefangen (3h von 3h 40min)
- Beispielcode recherchiert 

Selbsteinschätzung: 
- Blutiger Anfänger
