### ISSUE TITLE
Programmierumgebung einrichten

### ISSUE THREAD

**Issue by JohannMarthaus** [tBuddy00/Follow-Me-Roboter#7]
Jeder im Team muss eine funktionierende Programmierumgebung haben und mit dieser zurechtkommen!
Die Einrichtung bitte innerhalb dieser Woche erledigen.
Wer es erledigt hat kommentiert "Eingerichtet und funktioniert." unter diesem Issue.
Für Rückfragen stehe ich zu Verfügung.

Welche Programmierumgebung ist prinzipiell jedem selbst überlassen.
Beispiele sind Anaconda, PyCharm oder VisualStudioCode.

Wichtig ist das ihr in der Lage seid eine gewisse Formatierung (pep 8 Standard) zu befolgen, packages zu installieren und euch generell gut in der Umgebung euerer Wahl zurechtzufinden.

Für VisualStudioCode verlinke ich ein kurzes Video das ich gemacht habe - für die die Probleme haben eine Umgebung einzurichten. Über den gleichen Link findet ihr den Ordner mit dem demoskrip von https://www.geeksforgeeks.org/pedestrian-detection-using-opencv-python/ und dem Bild aus dem Video.

Link: https://1drv.ms/f/s!AlZqSMqH3IGR1HI66ypiQg0-R6RT?e=f3FAf8
Passwort: followme_123

**Comment by LucaKurth** [comment]
Eingerichtet und funktioniert

**Comment by tBuddy00** [comment]
Eingerichtet und funktioniert 👯‍♂️

**Comment by JohannMarthaus** [comment]
Eingerichtet und funktioniert

**Comment by cl-ire** [comment]
Eingerichtet und funktioniert
